name = "SU2"
uuid = "1c22364f-5a27-4a14-9ac2-9d0fe45c9f1b"
authors = ["Paulo José Saiz Jabardo"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
